# Generated by Django 3.0.5 on 2020-12-02 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('memberCount', models.IntegerField(default=0, verbose_name='Contador de miembros')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('identifier', models.CharField(default='6128cff887690d83a8b9', max_length=300, verbose_name='Identificador')),
                ('tutors', models.ManyToManyField(blank=True, related_name='tutores', to=settings.AUTH_USER_MODEL, verbose_name='Tutores')),
                ('users', models.ManyToManyField(blank=True, to='users.User', verbose_name='Miembros')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
    ]
