# Generated by Django 3.0.5 on 2020-11-17 19:08

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('memberCount', models.IntegerField(default=0, verbose_name='Contador de miembros')),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Creado en')),
                ('users', models.ManyToManyField(blank=True, to='users.User', verbose_name='Miembros')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='MessageForumGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Mensaje')),
                ('mimeType', models.FileField(default='null', upload_to='uploads/attach', verbose_name='Tipo de mensaje')),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha de creacion')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='Autor')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Groups', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
            },
        ),
    ]
