# Generated by Django 3.0.5 on 2020-11-06 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('memberCount', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=150)),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('users', models.ManyToManyField(to='users.User')),
            ],
        ),
    ]
