# Generated by Django 3.0.5 on 2020-12-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='identifier',
            field=models.CharField(default='afc8fbd53a49a7da1fa9', max_length=300, verbose_name='Identificador'),
        ),
    ]
