# Generated by Django 3.0.5 on 2020-12-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='identifier',
            field=models.CharField(default='a7c890d5778062b7f344', max_length=300, verbose_name='Identificador'),
        ),
    ]
