# Generated by Django 3.0.5 on 2020-12-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='identifier',
            field=models.CharField(default='a6db64256862fddbd54e', max_length=300, verbose_name='Identificador'),
        ),
    ]
