# Generated by Django 3.0.5 on 2020-11-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='identifier',
            field=models.CharField(default='d71d30a28647ea430bee', max_length=300, verbose_name='Identificador'),
        ),
    ]
