# Generated by Django 3.0.5 on 2020-12-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20201201_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='tutors',
        ),
        migrations.AddField(
            model_name='groups',
            name='deviceToken',
            field=models.CharField(default='', max_length=300, verbose_name='TokenDispositivo'),
        ),
    ]
