# Generated by Django 3.0.5 on 2020-11-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20201119_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='identifier',
            field=models.CharField(default='521e5a768876323df2f8', max_length=300, verbose_name='Identificador'),
        ),
    ]
