# Generated by Django 3.0.5 on 2020-12-01 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0003_auto_20201201_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='deviceToken',
        ),
        migrations.AddField(
            model_name='groups',
            name='tutors',
            field=models.ManyToManyField(blank=True, related_name='tutores', to=settings.AUTH_USER_MODEL, verbose_name='Tutores'),
        ),
    ]
