# Generated by Django 3.0.2 on 2020-11-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_forumgroup_messageforumgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumgroup',
            options={'verbose_name': 'Chat de Grupo', 'verbose_name_plural': 'Chats de Grupo'},
        ),
    ]
