# Generated by Django 3.0.2 on 2020-11-07 14:09

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201107_1509'),
        ('groups', '0005_auto_20201107_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumgroup',
            name='Group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Groups', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='forumgroup',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='forumgroup',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='messageforumgroup',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='messageforumgroup',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='messageforumgroup',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='messageforumgroup',
            name='forum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.ForumGroup', verbose_name='Foro'),
        ),
        migrations.AlterField(
            model_name='messageforumgroup',
            name='mimeType',
            field=models.FileField(default='null', upload_to='uploads/attach', verbose_name='Tipo de mensaje'),
        ),
    ]
