# Generated by Django 3.0.5 on 2020-11-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20201124_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='identifier',
            field=models.CharField(default='ae67d28befb505d4b15c', max_length=300, verbose_name='Identificador'),
        ),
    ]
