# Generated by Django 3.0.5 on 2020-12-01 12:20

import ckeditor.fields
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('shortDescription', models.CharField(max_length=600, verbose_name='Descripción corta')),
                ('fullDescription', ckeditor.fields.RichTextField(verbose_name='Descripción completa')),
                ('image', models.ImageField(default='null', upload_to=tasks.models.taskImageDirectoryPath, verbose_name='Icono')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('media', models.FileField(default='null', upload_to=tasks.models.taskMediaDirectoryPath, verbose_name='Archivo')),
                ('identifier', models.CharField(default='35a1aa7cf2ae6e2786c0', max_length=300, verbose_name='Identificador')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Category', verbose_name='Categoría')),
                ('users', models.ManyToManyField(blank=True, related_name='usuarios', to='users.User', verbose_name='Asignada a')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('comment', models.CharField(default='', max_length=800, verbose_name='Comentario')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task', verbose_name='Tarea')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tutor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=800, verbose_name='Opinion')),
                ('difficulty', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Dificultad')),
                ('utility', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Utilidad')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task', verbose_name='Tarea')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0, verbose_name='Total')),
                ('done', models.IntegerField(default=0, verbose_name='Completadas')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Category', verbose_name='Categoría')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='Usuario')),
            ],
        ),
    ]
