# Generated by Django 3.0.5 on 2020-12-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='identifier',
            field=models.CharField(default='236ea7502baf4a7e46ef', max_length=300, verbose_name='Identificador'),
        ),
    ]
