# Generated by Django 3.0.5 on 2020-11-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='identifier',
            field=models.CharField(default='3b5b66626d21407174ac', max_length=300, verbose_name='Identificador'),
        ),
    ]
