# Generated by Django 3.0.5 on 2020-11-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='identifier',
            field=models.CharField(default='a95b2c512616b0a6e1c0301aa77d8612aea1af4e40a4ebdb855f9d9cc4815738c85d9b0d537dabf1fa089c649d973e5aa681d9615f69577565a7edbd50cfd33d', max_length=300, verbose_name='Identificador'),
        ),
    ]
