# Generated by Django 3.0.5 on 2020-12-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='identifier',
            field=models.CharField(default='6c4937e7222f878c0640', max_length=300, verbose_name='Identificador'),
        ),
    ]
