# Generated by Django 3.0.5 on 2020-12-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201201_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='identifier',
            field=models.CharField(default='5ce053f715e81c547671', max_length=300, verbose_name='Identificador'),
        ),
    ]
