# Generated by Django 3.0.5 on 2020-11-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='identifier',
            field=models.CharField(default='5e262812d3169f1f1823', max_length=300, verbose_name='Identificador'),
        ),
    ]
