# Generated by Django 3.0.5 on 2020-11-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201116_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='identifier',
            field=models.CharField(default='31080fa4c4ce420791bd', max_length=300, verbose_name='Identificador'),
        ),
    ]
