# Generated by Django 3.0.5 on 2020-12-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201201_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='identifier',
            field=models.CharField(default='bfe0145a272ab2351894', max_length=300, verbose_name='Identificador'),
        ),
    ]
