# Generated by Django 3.0.5 on 2020-12-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20201201_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='identifier',
            field=models.CharField(default='d8dec971703e286bb09a', max_length=300, verbose_name='Identificador'),
        ),
    ]
