# Generated by Django 3.0.5 on 2020-11-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20201116_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='identifier',
            field=models.CharField(default='20dd2b3f5d5beffae442', max_length=300, verbose_name='Identificador'),
        ),
    ]
