# Generated by Django 3.0.5 on 2020-12-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20201201_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='identifier',
            field=models.CharField(default='f233c0f7cb7cc7778ac2', max_length=300, verbose_name='Identificador'),
        ),
    ]
