# Generated by Django 3.0.5 on 2020-11-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20201124_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='identifier',
            field=models.CharField(default='55c351f07032cf458bee', max_length=300, verbose_name='Identificador'),
        ),
    ]
