# Generated by Django 3.0.5 on 2020-12-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20201201_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='identifier',
            field=models.CharField(default='f80b26d85ddb833896ea', max_length=300, verbose_name='Identificador'),
        ),
    ]
