# Generated by Django 3.0.5 on 2020-11-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20201124_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='identifier',
            field=models.CharField(default='f79b879b65a05bf27ace', max_length=300, verbose_name='Identificador'),
        ),
    ]
