# Generated by Django 3.0.5 on 2020-12-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20201201_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='identifier',
            field=models.CharField(default='8b545cf1597724e427e9', max_length=300, verbose_name='Identificador'),
        ),
    ]
