# Generated by Django 3.0.5 on 2020-12-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='path',
            field=models.CharField(default=None, max_length=500, verbose_name='Tipo de mensaje'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='mimeType',
            field=models.CharField(default='.txt', max_length=100, verbose_name='Tipo de mensaje'),
        ),
    ]
