# Generated by Django 3.0.2 on 2020-11-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20201107_1316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='MessageForum',
        ),
    ]
