# Generated by Django 3.0.5 on 2020-11-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('phoneNumber', models.CharField(max_length=150)),
                ('profileImage', models.ImageField(default='null', upload_to='')),
                ('token', models.CharField(max_length=300)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
