# Generated by Django 3.0.2 on 2020-11-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='800e8fe757bf12fb7d607dfa07ea94ed18da014e3643c2cc8d689ad84707884a2faf7a80d31782d8696a5d05a3dfc62300a090baa3f3413cd229181e9b168b6f', max_length=300),
        ),
    ]
