# Generated by Django 3.0.5 on 2020-12-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='createdAt',
        ),
        migrations.AddField(
            model_name='user',
            name='deviceToken',
            field=models.CharField(default='', max_length=300, verbose_name='TokenDispositivo'),
        ),
    ]
