# Generated by Django 3.0.5 on 2020-11-25 00:23

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201124_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictograms',
            name='image',
            field=models.ImageField(default='null', upload_to=users.models.pictogram_directory_path, verbose_name='Imagen de Pictograma'),
        ),
    ]
