# Generated by Django 3.0.2 on 2020-11-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_forum_groups_log_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictograms',
            name='value',
        ),
    ]
