# Generated by Django 3.0.2 on 2020-11-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201107_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='7ac60ef903d688356cf8f5cc83479b9664ba11dfa2f83ff5489b367755530076c78dc4c28702c3e57bdacbb96c83f727fa43a28ad164eef01e39ae45c2d4484c', max_length=300),
        ),
    ]
