# Generated by Django 3.0.2 on 2020-11-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201107_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='6886ebd2c6858a5bba04aca8a17726b8c135b894e3aa060297cd0664640a63d42a59bd293276e91a40c23328bde3e796473d178f2290ab2947635f441bd29e6d', max_length=300),
        ),
    ]
