# Generated by Django 3.0.2 on 2020-11-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201107_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='b6e69119a69021bea70f6b333968495423f38643d753296af3407d1bfbe44e3c817ec7f5c87f3aa86391c7eb77b900ee095947c2933cb72d1175134c6b72e0e0', max_length=300),
        ),
    ]
