# Generated by Django 3.0.5 on 2020-11-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201104_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='1e7326d7fd38932c723f047ba7594870ced02f8cb849ef2de46fb11608476855db6766bcb5796cd8c3c51cae7af5d37cb20c0b9e9184d99b3a876ed7965d80fd', max_length=300),
        ),
    ]
