# Generated by Django 3.0.2 on 2020-11-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201107_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='afd1b52d2779446582ac85b29336a10f09afdcf4dbf48f7a57acc3011da0949f5f16801521b228a6e2e4707cabaafb9c677194760a31ba2ae6510766eba08b5c', max_length=300),
        ),
    ]
