# Generated by Django 3.0.2 on 2020-11-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201107_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='6f713424d87ad166808cbf6c049801bb55de8c034dc59c704004dab2df595ded27a8834d265341223df88d409298b65b2cc8c3fd89fceaf96856532fd4c1a68b', max_length=300),
        ),
    ]
