# Generated by Django 3.0.2 on 2020-11-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201107_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='7ad555f454533cb2d211a4a8853e076f024559914b5b769daf3f975896f48398acb7aec4f9985b72929a53d897e416acd018f427f86d966bbe60873c8579283c', max_length=300),
        ),
    ]
