# Generated by Django 3.0.5 on 2020-11-07 14:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_auto_20201107_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='d462d518b18ee68d0e38ef3cec7fed1e24192f9eee7f719116ebd9db80126405ba7e29248bbdbcdc17bbc584e82c0a0bc733c872bf5956a5c4bd9f9ca69279cd', max_length=300),
        ),
        migrations.CreateModel(
            name='ForumUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tutor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Chat de Usuario',
                'verbose_name_plural': 'Chats de Grupo',
            },
        ),
    ]
