# Generated by Django 3.0.2 on 2020-11-07 20:33

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201107_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumuser',
            options={'verbose_name': 'Chat de Usuario', 'verbose_name_plural': 'Chats de Usuario'},
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='170bbf3b887d2a43ab19c096b8e8b7dd7a38b4dd4ac636eb087ce450f34f9f2e17b0844777d548e2b615af58b8c809152bf836a68e073a14061db90554d5d3f8', max_length=300),
        ),
        migrations.CreateModel(
            name='MessageForumUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Mensaje')),
                ('mimeType', models.FileField(default='null', upload_to='uploads/attach', verbose_name='Tipo de mensaje')),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha de creacion')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='Autor')),
                ('forum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ForumUser', verbose_name='Conversacion')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
            },
        ),
    ]
