# Generated by Django 3.0.2 on 2020-11-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201107_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='fcbb75c398cc96afcb53dcea17b89f8442c120a9004a38b230b596ce281225f391331c5473775511a9869efb89aaf1dcfc44da23df1608add983753108fe8886', max_length=300),
        ),
    ]
