# Generated by Django 3.0.2 on 2020-11-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201108_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='78988a28f01e281781b572c530b08440f2fed02a023da91c2f5dec7a53038e5caf694b570afa922ba3f36f2eccf8334e59c34d964eed198e1aee9dbaeb118720', max_length=300),
        ),
    ]
