# Generated by Django 3.0.5 on 2020-11-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201108_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='61ee622afa471a1f2dca64fb4d017674ffd3322ff18c8a20df254ec33782d4e6f7633452d69aa2ff961482db984249ae8ec6d80813d3dc7e68a7bb720220c876', max_length=300),
        ),
    ]
