# Generated by Django 3.0.5 on 2020-11-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201112_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='c89b69c9de4f64ab0accf92c46e1669f9a77ac9f6e8c7d56131453f21260aa74a10452b9d160a263a6b2b28016900f8c54e74b28da1f27f86291c3c010365359', max_length=300),
        ),
    ]
