# Generated by Django 3.0.5 on 2020-11-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201112_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='974fc8486ee459ad51fbf9ab41357dfccb8aaf2f8a8c46792b7042a505f01414b7d82783d5d8dbf5c5a7c5785b73444400cd026f19b2945e33da8e1a9315c1e5', max_length=300),
        ),
    ]
