# Generated by Django 3.0.5 on 2020-11-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20201112_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='a276d2eb91a8b78f76de1e9fc8be3a215c52071c28268b27ed9d43dfe5405e4269e93308c6e7d4806ebd6271a26a2e7752b68c11df61245348f47dcaf119fc91', max_length=300),
        ),
    ]
