# Generated by Django 3.0.5 on 2020-11-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20201113_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='null', max_length=300),
        ),
    ]
